name: merchant
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.2.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8    # Dùng cho giao diện iOS
  device_preview: ^1.2.0     # Giúp xem trước giao diện trên nhiều thiết bị khác nhau
  get: ^4.7.2                # Quản lý trạng thái và điều hướng
  accordion: ^2.3.0          # Tạo giao diện Accordion (các phần mở rộng/thu gọn)
  percent_indicator: ^4.2.3  # Hiển thị thanh phần trăm
  intl: ^0.19.0              # Hỗ trợ định dạng ngày tháng, tiền tệ
  get_storage: ^2.1.1        # Lưu trữ dữ liệu
  http: ^1.3.0               # Gửi request HTTP (API call)
  flutter_slidable: ^3.1.2   # Tạo hiệu ứng trượt cho các item
  timeline_tile: ^2.0.0      # Tạo dòng thời gian (timeline) cho giao diện
  dropdown_button2: ^2.3.9   # Tạo Dropdown tùy biến


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

