name: merchant
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.2.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  get: ^4.7.2
  fl_chart: ^0.66.0
  accordion: ^2.3.0
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

