import '../models/debt_model.dart';
import '../models/login_model.dart';
import '../models/point.dart';
import '../models/schedule_model.dart';
import '../models/truck.dart';

List<point> mockPoints = [
  point(
    1,
    "CTG_001",
    "Công ty Vệ Sinh Xanh",
    "Số 123, Đường Nguyễn Trãi, Quận 1, TP.HCM",
    "Khu vực 1",
    101,
    201,
    "Đã sắp",
    DateTime.now().subtract(const Duration(days: 1)), // Hôm qua
    "Rác thải hữu cơ",
    120.5,
    150000,
    ["https://example.com/image1.jpg"],
    301,
    null,
    null,
    [],
    [],
  ),
  point(
    2,
    "CTG_002",
    "Công ty Môi Trường Tái Chế",
    "Số 456, Đường Lê Lợi, Quận 3, TP.HCM",
    "Khu vực 2",
    102,
    202,
    "Chưa sắp",
    DateTime.now().add(const Duration(days: 1)), // Ngày mai
    "Rác thải tái chế",
    85.0,
    100000,
    [],
    302,
    null,
    null,
    [],
    [],
  ),
  point(
    3,
    "CTG_003",
    "Công ty Vệ Sinh Đô Thị",
    "Số 789, Đường Điện Biên Phủ, Quận 10, TP.HCM",
    "Khu vực 3",
    103,
    203,
    "Đã sắp",
    DateTime.now().add(const Duration(days: 1)), // Hôm nay
    "Rác thải nguy hại",
    45.2,
    200000,
    [],
    303,
    null,
    null,
    [],
    [],
  ),
  point(
    4,
    "CTG_004",
    "Công ty Thu Gom Rác Thải",
    "Số 321, Đường Hai Bà Trưng, Quận 1, TP.HCM",
    "Khu vực 1",
    104,
    204,
    "Chưa sắp",
    DateTime.now().add(const Duration(days: 3)), // Ngày 3
    "Rác sinh hoạt",
    75.3,
    80000,
    [],
    304,
    null,
    null,
    [],
    [],
  ),
  point(
    5,
    "CTG_005",
    "Công ty Rác Công Nghiệp",
    "Số 654, Đường Trần Hưng Đạo, Quận 5, TP.HCM",
    "Khu vực 4",
    105,
    205,
    "Đã sắp",
    DateTime.now().subtract(const Duration(days: 2)), // Hôm kia
    "Rác công nghiệp",
    130.0,
    250000,
    [],
    305,
    null,
    null,
    [],
    [],
  ),
];

final List<Schedule> schedules = [
  Schedule(
    id: '001',
    companyName: 'Công Ty CP SX TM Sáng Việt Ty CP SX TM Sáng Việt  ',
    description: 'Gom đủ không ghi phiếu',
    from: 'Thủ Thừa (Long An)',
    to: 'Bình Tân (TP.HCM)',
    contactName: 'Chị Giao',
    contactPhone: '0909123456',
    cargoType: 'Khoáng',
    datetime: DateTime(2025, 4, 5, 16, 30),
    note: "Gom đủ không ghi phiếu",
    price: 2400000,
    status: 'Đã thu gom',
  ),
  Schedule(
    id: '002',
    companyName: 'Công Ty TNHH Vận Tải Minh Phúc',
    description: 'Chở hàng có phiếu đầy đủ',
    from: 'Tân An (Long An)',
    to: 'Quận 9 (TP.HCM)',
    contactName: 'Anh Minh',
    contactPhone: '0911222333',
    cargoType: 'Sắt vụn',
    datetime: DateTime(2025, 4, 5, 16, 30),
    note: "Gom đủ không ghi phiếu",
    status: 'Chưa thu gom',
    price: 1800000,
  ),
  Schedule(
    id: '003',
    companyName: 'CTY CP TM Tân Thịnh',
    description: 'Hàng hóa không cần biên bản',
    from: 'Bến Lức (Long An)',
    to: 'Thủ Đức (TP.HCM)',
    contactName: 'Chị Hương',
    contactPhone: '0988777666',
    cargoType: 'Giấy tái chế',
    datetime: DateTime(2025, 4, 5, 16, 30),
    status: 'Chưa thu gom',
    note: "Gom đủ không ghi phiếu",
    price: 2150000,
  ),
  Schedule(
    id: '004',
    companyName: 'Công Ty CP SX TM Sáng Việt',
    description: 'Gom đủ không ghi phiếu',
    from: 'Thủ Thừa (Long An)',
    to: 'Bình Tân (TP.HCM)',
    contactName: 'Chị Giao',
    contactPhone: '0909123456',
    cargoType: 'Khoáng',
    datetime: DateTime(2025, 4, 15, 16, 30),
    note: "Gom đủ không ghi phiếu",
    price: 2400000,
    status: 'Đã thu gom',
  ),
  Schedule(
    id: '005',
    companyName: 'CTY CP TM Tân Phát',
    description: 'Hàng hóa không cần biên bản',
    from: 'Bến Lức (Long An)',
    to: 'Thủ Đức (TP.HCM)',
    contactName: 'Chị Hương',
    contactPhone: '0988777666',
    cargoType: 'Giấy tái chế',
    datetime: DateTime(2025, 4, 15, 16, 30),
    status: 'Chưa thu gom',
    note: "Gom đủ không ghi phiếu",
    price: 2150000,
  ),
  Schedule(
    id: '006',
    companyName: 'Công Ty CP SX TM Sáng Việt',
    description: 'Gom đủ không ghi phiếu',
    from: 'Thủ Thừa (Long An)',
    to: 'Bình Tân (TP.HCM)',
    contactName: 'Chị Giao',
    contactPhone: '0909123456',
    cargoType: 'Khoáng',
    datetime: DateTime(2025, 4, 15, 16, 30),
    note: "Gom đủ không ghi phiếu",
    price: 2400000,
    status: 'Đã thu gom',
  ),
  Schedule(
    id: '007',
    companyName: 'CTY CP TM Tân Tiến CP TM Tân Tiến',
    description: 'Hàng hóa không cần biên bản',
    from: 'Bến Lức (Long An)',
    to: 'Thủ Đức (TP.HCM)',
    contactName: 'Chị Hương',
    contactPhone: '0988777666',
    cargoType: 'Giấy tái chế',
    datetime: DateTime(2025, 4, 15, 16, 30),
    status: 'Chưa thu gom',
    note: "Gom đủ không ghi phiếu",
    price: 2150000,
  ),
];

final List<Map<String, String>> images = [
  {
    'image': 'assets/images/temp.png',
    'title': 'Mời thầu vận chuyển vải vụn tại khu vực miền tây...',
  },
  {
    'image': 'assets/images/temp.png',
    'title': 'Mời thầu vận chuyển vải vụn tại khu vực miền tây...',
  },
];

final List<Map<String, String>> collectedItems = [
  {
    "id": "Bãi rác Nam Sơn",
    "tenHangHoa": "Chất thải nguy hại",
    "kl": "10000",
  },
  {
    "id": "Nhà máy phân compost",
    "tenHangHoa": "chất thải sinh hoạt",
    "kl": "2500",
  },
];

List<Map<String, dynamic>> allData = [
  {
    "name": "Thuê nhân công",
    "quantity": 10,
    "price": "15.000",
    "total": "150.000",
  },
  {
    "name": "Bốc vác xuống",
    "quantity": 25,
    "price": "5.000",
    "total": "125.000",
  },
];

final List<truck> mockTrucks = [
  truck(
      1, '51A-12345', 'Hyundai-0123', 'Hyundai', 'Thùng kín', 5, 'Đã sắp lịch'),
  truck(5, '51E-56789', 'Isuzu-0456', 'Isuzu', 'Thùng bạt', 8, 'Chưa sắp lịch'),
  truck(3, '51C-34567', 'Hino-0123', 'Hino', 'Thùng bạt', 15, 'Chưa sắp lịch'),
  truck(2, '51B-23456', 'Isuzu-0123', 'Isuzu', 'Thùng kín', 8, 'Đã sắp lịch'),
  truck(4, '51D-45678', 'Hyundai-0456', 'Hyundai', 'Thùng kín', 5,
      'Chưa sắp lịch'),
];

final List<Map<String, String>> truckData = [
  {
    'code': 'CTG-75164',
    'company': 'Công ty XYZ,Công ty XYZ,Công ty XYZ,Công ty XYZ',
    'driver': 'Lê Thị Cúc',
    'status': 'Đã thu gom',
  },
  {
    'code': 'CTG-75164',
    'company': 'Công ty XYZ',
    'driver': 'Lê Thị Cúc',
    'status': 'Đã thu gom',
  },
  {
    'code': 'CTG-75164',
    'company': 'Công ty XYZ',
    'driver': 'Lê Thị Cúc',
    'status': 'Đã thu gom',
  },
  {
    'code': 'CTG-75163',
    'company': 'Công ty ABC',
    'driver': 'Trần Văn Bình Bình',
    'status': 'Đã thu gom',
  },
];

final List<LoginModel> mockUsers = [
  LoginModel(
    username: "Nguyễn Văn Cê",
    email: "merchant@gmail.com",
    password: "123456",
  ),
  LoginModel(
    username: "Nguyễn Văn Bê",
    email: "merchant1@gmail.com",
    password: "password",
  ),
];

final List<DebtModel> mockDebts = [
  DebtModel(
    code: "CN001",
    title: "Công nợ tháng 4",
    date: "14/05/2025",
    amount: 73000000,
    status: "Chưa thanh toán",
    progress: "0/3",
  ),
  DebtModel(
    code: "CN002",
    title: "Công nợ tháng 3",
    date: "13/05/2025",
    amount: 55000500,
    status: "Đã thanh toán",
    progress: "4/4",
  ),
  DebtModel(
    code: "CN006",
    title: "Công nợ tháng 3",
    date: "15/05/2025",
    amount: 120000000,
    status: "Đã thanh toán",
    progress: "4/4",
  ),
  DebtModel(
    code: "CN007",
    title: "Công nợ tháng 3",
    date: "15/05/2025",
    amount: 50500000,
    status: "Đã thanh toán",
    progress: "4/4",
  ),
  DebtModel(
    code: "CN004",
    title: "Công nợ tháng 3",
    date: "13/05/2025",
    amount: 30500000,
    status: "Hết hạn",
    progress: "2/4",
  ),
  DebtModel(
    code: "CN003",
    title: "Công nợ tháng 3",
    date: "12/05/2025",
    amount: 42000100,
    status: "Thanh toán một phần",
    progress: "2/4",
  ),
];
