import '../models/schedule_model.dart';
import '../models/truck_model.dart';

final List<Schedule> schedules = [
  Schedule(
    id: '001',
    companyName: 'Công Ty CP SX TM Sáng Việt',
    description: 'Gom đủ không ghi phiếu',
    from: 'Thủ Thừa (Long An)',
    to: 'Bình Tân (TP.HCM)',
    contactName: 'Chị Giao',
    contactPhone: '0909123456',
    cargoType: 'Khoáng',
    datetime: DateTime(2025, 4, 5, 16, 30),
    note: "Gom đủ không ghi phiếu",
    price: 2400000,
    status: 'Đã thu gom',
  ),
  Schedule(
    id: '002',
    companyName: 'Công Ty TNHH Vận Tải Minh Phúc',
    description: 'Chở hàng có phiếu đầy đủ',
    from: 'Tân An (Long An)',
    to: 'Quận 9 (TP.HCM)',
    contactName: 'Anh Minh',
    contactPhone: '0911222333',
    cargoType: 'Sắt vụn',
    datetime: DateTime(2025, 4, 5, 16, 30),
    note: "Gom đủ không ghi phiếu",
    status: 'Chưa thu gom',
    price: 1800000,
  ),
  Schedule(
    id: '003',
    companyName: 'CTY CP TM Tân Thịnh',
    description: 'Hàng hóa không cần biên bản',
    from: 'Bến Lức (Long An)',
    to: 'Thủ Đức (TP.HCM)',
    contactName: 'Chị Hương',
    contactPhone: '0988777666',
    cargoType: 'Giấy tái chế',
    datetime: DateTime(2025, 4, 5, 16, 30),
    status: 'Chưa thu gom',
    note: "Gom đủ không ghi phiếu",
    price: 2150000,
  ),
  Schedule(
    id: '004',
    companyName: 'Công Ty CP SX TM Sáng Việt',
    description: 'Gom đủ không ghi phiếu',
    from: 'Thủ Thừa (Long An)',
    to: 'Bình Tân (TP.HCM)',
    contactName: 'Chị Giao',
    contactPhone: '0909123456',
    cargoType: 'Khoáng',
    datetime: DateTime(2025, 4, 5, 16, 30),
    note: "Gom đủ không ghi phiếu",
    price: 2400000,
    status: 'Đã thu gom',
  ),
  Schedule(
    id: '005',
    companyName: 'CTY CP TM Tân Phát',
    description: 'Hàng hóa không cần biên bản',
    from: 'Bến Lức (Long An)',
    to: 'Thủ Đức (TP.HCM)',
    contactName: 'Chị Hương',
    contactPhone: '0988777666',
    cargoType: 'Giấy tái chế',
    datetime: DateTime(2025, 4, 5, 16, 30),
    status: 'Chưa thu gom',
    note: "Gom đủ không ghi phiếu",
    price: 2150000,
  ),
  Schedule(
    id: '006',
    companyName: 'Công Ty CP SX TM Sáng Việt',
    description: 'Gom đủ không ghi phiếu',
    from: 'Thủ Thừa (Long An)',
    to: 'Bình Tân (TP.HCM)',
    contactName: 'Chị Giao',
    contactPhone: '0909123456',
    cargoType: 'Khoáng',
    datetime: DateTime(2025, 4, 5, 16, 30),
    note: "Gom đủ không ghi phiếu",
    price: 2400000,
    status: 'Đã thu gom',
  ),
  Schedule(
    id: '007',
    companyName: 'CTY CP TM Tân Tiến',
    description: 'Hàng hóa không cần biên bản',
    from: 'Bến Lức (Long An)',
    to: 'Thủ Đức (TP.HCM)',
    contactName: 'Chị Hương',
    contactPhone: '0988777666',
    cargoType: 'Giấy tái chế',
    datetime: DateTime(2025, 4, 5, 16, 30),
    status: 'Chưa thu gom',
    note: "Gom đủ không ghi phiếu",
    price: 2150000,
  ),
];

final List<Map<String, String>> images = [
  {
    'image': 'assets/images/temp.png',
    'title': 'Mời thầu vận chuyển vải vụn tại khu vực miền tây...',
  },
  {
    'image': 'assets/images/temp.png',
    'title': 'Mời thầu vận chuyển vải vụn tại khu vực miền tây...',
  },
];

final List<Map<String, String>> collectedItems = [
  {
    "id": "136685",
    "tenHangHoa":
        "Chất hấp thụ, vật liệu lọc, giẻ lau, vải bảo vệ thải bị nhiễm chất thành phần nguy hại",
    "kl": "10",
  },
  {
    "id": "136686",
    "tenHangHoa": "Thiết bị điện tử thải bỏ",
    "kl": "25",
  },
];

List<Map<String, dynamic>> allData = [
  {
    "name": "Vận chuyển",
    "quantity": 10,
    "price": "15.000",
    "total": "150.000",
  },
  {
    "name": "Bốc vác lên",
    "quantity": 25,
    "price": "5.000",
    "total": "125.000",
  },
];

final List<TruckModel> trucks = [
  TruckModel(
    name: "Container 001 Container 001 Container 001",
    licensePlate: "51C-123.45",
    brand: "Hyundai",
    code: "CTR001",
    type: "Container",
    status: "chờ chuyến",
    loadCapacity: 1.5,
  ),
  TruckModel(
    name: "Container 002",
    licensePlate: "51C-543.21",
    brand: "Hyundai",
    code: "CTR002",
    type: "Container",
    status: "có chuyến",
    loadCapacity: 2.5,
  ),
  TruckModel(
    name: "Container 003",
    licensePlate: "51C-678.90",
    brand: "Hyundai",
    code: "CTR003",
    type: "Container",
    status: "bảo trì",
    loadCapacity: 3,
  ),
  TruckModel(
    name: "Container 004",
    licensePlate: "51C-888.88",
    brand: "Hyundai",
    code: "CTR004",
    type: "Container",
    status: "chờ chuyến",
    loadCapacity: 1,
  ),
  TruckModel(
    name: "Bán tải 001",
    licensePlate: "60C-111.22",
    brand: "Hyundai",
    code: "BT001",
    type: "Bán tải",
    status: "bảo trì",
    loadCapacity: 2.5,
  ),
  TruckModel(
    name: "Bán tải 002",
    licensePlate: "60C-222.33",
    brand: "Hyundai",
    code: "BT002",
    type: "Bán tải",
    status: "chờ chuyến",
    loadCapacity: 3,
  ),
  TruckModel(
    name: "Bán tải 003",
    licensePlate: "60C-333.44",
    brand: "Hyundai",
    code: "BT003",
    type: "Bán tải",
    status: "chờ chuyến",
    loadCapacity: 4.5,
  ),
  TruckModel(
    name: "Bán tải 004",
    licensePlate: "60C-444.55",
    brand: "Hyundai",
    code: "BT004",
    type: "Bán tải",
    status: "có chuyến",
    loadCapacity: 2,
  ),
];

final List<Map<String, String>> truckData = [
  {
    'code': 'CTG-75164',
    'company': 'Công ty XYZ,Công ty XYZ,Công ty XYZ,Công ty XYZ',
    'driver': 'Lê Thị Cúc',
    'status': 'Đã thu gom',
  },
  {
    'code': 'CTG-75164',
    'company': 'Công ty XYZ',
    'driver': 'Lê Thị Cúc',
    'status': 'Đã thu gom',
  },
  {
    'code': 'CTG-75164',
    'company': 'Công ty XYZ',
    'driver': 'Lê Thị Cúc',
    'status': 'Đã thu gom',
  },
  {
    'code': 'CTG-75163',
    'company': 'Công ty ABC',
    'driver': 'Trần Văn Bình Bình',
    'status': 'Đã thu gom',
  },
];
